"""
=============================================================================
Create Greyscale-Inverted Dataset from Visible Images
=============================================================================

Reads every visible image, converts to greyscale, inverts (255 - pixel),
and saves as a 3-channel BGR image so YOLO can load it normally.

Labels are copied from labels/visible/ since the bounding boxes are
identical.  A new YAML config is generated for training.

Usage:
    python create_greyscale_inversion.py

Output:
    datasets/kaist_processed/images/greyscale_inversion/train/*.jpg
    datasets/kaist_processed/images/greyscale_inversion/val/*.jpg
    datasets/kaist_processed/labels/greyscale_inversion/train/*.txt
    datasets/kaist_processed/labels/greyscale_inversion/val/*.txt
    datasets/kaist_processed/kaist_greyscale_inversion.yaml
=============================================================================
"""

import os
import shutil

import cv2

# =============================================================================
# PATHS
# =============================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
DATASET_ROOT = os.path.join(PROJECT_ROOT, "datasets", "kaist_processed")

SRC_IMG_DIR = os.path.join(DATASET_ROOT, "images", "visible")
DST_IMG_DIR = os.path.join(DATASET_ROOT, "images", "greyscale_inversion")

SRC_LBL_DIR = os.path.join(DATASET_ROOT, "labels", "visible")
DST_LBL_DIR = os.path.join(DATASET_ROOT, "labels", "greyscale_inversion")

YAML_PATH = os.path.join(DATASET_ROOT, "kaist_greyscale_inversion.yaml")

SPLITS = ["train", "val"]


# =============================================================================
# IMAGE CONVERSION
# =============================================================================

def convert_image(src_path: str, dst_path: str):
    """Read an image, convert to greyscale, invert, save as 3-channel."""
    img = cv2.imread(src_path)
    if img is None:
        return False
    grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    inverted = 255 - grey
    bgr = cv2.cvtColor(inverted, cv2.COLOR_GRAY2BGR)
    cv2.imwrite(dst_path, bgr)
    return True


# =============================================================================
# MAIN
# =============================================================================

def main():
    print("=" * 70)
    print("Creating greyscale-inverted dataset from visible images")
    print("=" * 70)

    for split in SPLITS:
        # --- Convert images ---
        src_dir = os.path.join(SRC_IMG_DIR, split)
        dst_dir = os.path.join(DST_IMG_DIR, split)
        os.makedirs(dst_dir, exist_ok=True)

        files = sorted([
            f for f in os.listdir(src_dir)
            if f.lower().endswith((".jpg", ".jpeg", ".png"))
        ])
        total = len(files)
        print(f"\n[{split}] Converting {total} images...")

        for i, fname in enumerate(files):
            src_path = os.path.join(src_dir, fname)
            dst_path = os.path.join(dst_dir, fname)
            convert_image(src_path, dst_path)

            if (i + 1) % 2000 == 0 or (i + 1) == total:
                print(f"  {i + 1}/{total} images converted")

        # --- Copy labels ---
        src_lbl = os.path.join(SRC_LBL_DIR, split)
        dst_lbl = os.path.join(DST_LBL_DIR, split)
        os.makedirs(dst_lbl, exist_ok=True)

        lbl_files = [f for f in os.listdir(src_lbl) if f.endswith(".txt")]
        print(f"[{split}] Copying {len(lbl_files)} label files...")

        for fname in lbl_files:
            shutil.copy2(
                os.path.join(src_lbl, fname),
                os.path.join(dst_lbl, fname),
            )

    # --- Generate YAML config ---
    # Write both Docker (/workspace) and Windows paths so it works in both
    yaml_content = (
        "# KAIST Pedestrian Detection Dataset - Greyscale inverted images\n"
        "# Auto-generated by create_greyscale_inversion.py\n"
        "\n"
        "path: /workspace/datasets/kaist_processed\n"
        "train: /workspace/datasets/kaist_processed/images/greyscale_inversion/train\n"
        "val: /workspace/datasets/kaist_processed/images/greyscale_inversion/val\n"
        "\n"
        "# Class configuration\n"
        "nc: 1\n"
        "names: ['person']\n"
    )

    with open(YAML_PATH, "w") as f:
        f.write(yaml_content)
    print(f"\nSaved dataset config: {YAML_PATH}")

    print("\nDone! You can now train with:")
    print("  docker compose up train-greyscale-inversion")
    print("  # or: python train.py --modality greyscale_inversion")


if __name__ == "__main__":
    main()
