"""
=============================================================================
Evaluation Script: Subgroup Analysis Using Preprocessing Metadata
=============================================================================

This script evaluates YOLOv8 predictions against ground truth on the
validation set, then merges results with the preprocessing metadata CSVs
to analyse detection performance across subgroups.

The goal is to determine whether certain subgroups are systematically
harder to detect, which helps assess the impact of the thermal-to-visible
translation model on different object categories.

Subgroups analysed:
    - Day vs Night (from KAIST set ID mapping)
    - Object size (small / medium / large)
    - Occlusion level (none / partial / heavy)
    - Crowd density (number of people per frame)
    - Truncation (truncated vs not)
    - Overlap (has overlapping neighbour vs not)

Output CSVs  (saved to OD/eval_results/):
    per_image_results_{modality}.csv   -- per-image TP/FP/FN + frame metadata
    per_object_results_{modality}.csv  -- per-GT-object detected/missed + metadata
    subgroup_summary_{modality}.csv    -- aggregated metrics by subgroup

Usage:
    python evaluate.py                                        # visible, best.pt
    python evaluate.py --modality thermal                     # thermal model
    python evaluate.py --weights runs/kaist_visible/weights/best.pt
    python evaluate.py --conf 0.3                             # custom confidence
=============================================================================
"""

import argparse
import os
import numpy as np
import pandas as pd
import cv2
from collections import defaultdict
from typing import List, Dict, Tuple, Optional

from ultralytics import YOLO


# =============================================================================
# PATHS
# =============================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

DATASET_ROOT = os.path.join(PROJECT_ROOT, "datasets", "kaist_processed")
METADATA_DIR = os.path.join(DATASET_ROOT, "metadata")

# Preprocessing metadata CSVs (generated by the preprocessing pipeline)
FRAME_METADATA_CSV = os.path.join(METADATA_DIR, "frame_metadata.csv")
OBJECT_METADATA_CSV = os.path.join(METADATA_DIR, "object_metadata.csv")

# Default weights (after training)
RUNS_DIR = os.path.join(SCRIPT_DIR, "runs")

# Evaluation output directory
EVAL_OUTPUT_DIR = os.path.join(SCRIPT_DIR, "eval_results")

# Detection evaluation thresholds
IOU_THRESHOLD = 0.5
DEFAULT_CONF = 0.25

# Background border for per-object quality features
BG_BORDER_PX = 15


# =============================================================================
# GROUND TRUTH LOADING
# =============================================================================

def load_yolo_labels(label_path: str) -> List[Tuple[int, float, float, float, float]]:
    """
    Load YOLO-format labels from a .txt file.

    Returns:
        List of (class_id, x_center, y_center, width, height) — all normalised.
    """
    if not os.path.exists(label_path):
        return []

    labels = []
    with open(label_path, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 5:
                cls = int(parts[0])
                x, y, w, h = (
                    float(parts[1]), float(parts[2]),
                    float(parts[3]), float(parts[4]),
                )
                labels.append((cls, x, y, w, h))
    return labels


def yolo_to_xyxy(cx: float, cy: float, w: float, h: float,
                 img_size: int = 512) -> Tuple[float, float, float, float]:
    """Convert normalised YOLO centre format to pixel xyxy."""
    x1 = (cx - w / 2) * img_size
    y1 = (cy - h / 2) * img_size
    x2 = (cx + w / 2) * img_size
    y2 = (cy + h / 2) * img_size
    return x1, y1, x2, y2


def compute_iou_xyxy(box1, box2) -> float:
    """IoU between two boxes in (x1, y1, x2, y2) pixel format."""
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    if x1 >= x2 or y1 >= y2:
        return 0.0

    inter = (x2 - x1) * (y2 - y1)
    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
    union = area1 + area2 - inter
    return inter / union if union > 0 else 0.0


# =============================================================================
# PER-OBJECT IMAGE QUALITY FEATURES
# =============================================================================

def load_image_grayscale(img_path: str) -> Optional[np.ndarray]:
    """Load an image and convert to single-channel greyscale uint8."""
    img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
    if img is None:
        return None
    if len(img.shape) == 3 and img.shape[2] == 3:
        return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    if len(img.shape) == 3 and img.shape[2] == 1:
        return img[:, :, 0]
    return img


def compute_object_quality_features(
    img_gray: np.ndarray,
    x1: int, y1: int, x2: int, y2: int,
    img_h: int, img_w: int,
    border_px: int = BG_BORDER_PX,
) -> Dict[str, float]:
    """
    Compute image-quality features for a single object bounding box.

    Returns dict with: object_brightness, object_contrast, bg_brightness,
    bg_contrast, fg_bg_diff, object_edge_strength, object_blur.
    """
    nan_result = {
        "object_brightness": float("nan"),
        "object_contrast": float("nan"),
        "bg_brightness": float("nan"),
        "bg_contrast": float("nan"),
        "fg_bg_diff": float("nan"),
        "object_edge_strength": float("nan"),
        "object_blur": float("nan"),
    }

    # Bbox must be at least 3x3 for Sobel/Laplacian
    if (x2 - x1) < 3 or (y2 - y1) < 3:
        return nan_result

    crop = img_gray[y1:y2, x1:x2]
    if crop.size == 0:
        return nan_result

    obj_brightness = float(np.mean(crop))
    obj_contrast = float(np.std(crop))

    # Background: expanded bbox minus the object region
    bx1 = max(0, x1 - border_px)
    by1 = max(0, y1 - border_px)
    bx2 = min(img_w, x2 + border_px)
    by2 = min(img_h, y2 + border_px)

    bg_region = img_gray[by1:by2, bx1:bx2].copy()
    mask = np.ones(bg_region.shape, dtype=bool)
    mask[y1 - by1:y2 - by1, x1 - bx1:x2 - bx1] = False
    bg_pixels = bg_region[mask]

    if bg_pixels.size > 0:
        bg_brightness = float(np.mean(bg_pixels))
        bg_contrast = float(np.std(bg_pixels))
    else:
        bg_brightness = float("nan")
        bg_contrast = float("nan")

    fg_bg_diff = (abs(obj_brightness - bg_brightness)
                  if not np.isnan(bg_brightness) else float("nan"))

    # Edge strength (mean Sobel magnitude)
    sobel_x = cv2.Sobel(crop, cv2.CV_64F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(crop, cv2.CV_64F, 0, 1, ksize=3)
    edge_strength = float(np.mean(np.sqrt(sobel_x**2 + sobel_y**2)))

    # Blur measure (Laplacian variance — higher = sharper)
    laplacian = cv2.Laplacian(crop, cv2.CV_64F)
    blur_var = float(np.var(laplacian))

    return {
        "object_brightness": round(obj_brightness, 4),
        "object_contrast": round(obj_contrast, 4),
        "bg_brightness": round(bg_brightness, 4),
        "bg_contrast": round(bg_contrast, 4),
        "fg_bg_diff": round(fg_bg_diff, 4),
        "object_edge_strength": round(edge_strength, 4),
        "object_blur": round(blur_var, 4),
    }


# =============================================================================
# PER-IMAGE EVALUATION
#   For each image: match predictions to ground truth using greedy IoU
#   matching (highest-confidence prediction matched first).
# =============================================================================

def evaluate_image(
    pred_boxes: np.ndarray,
    pred_confs: np.ndarray,
    gt_labels: List[Tuple[int, float, float, float, float]],
    img_size: int = 512,
) -> Dict:
    """
    Match predictions to GT for one image.

    Returns:
        Dict with tp, fp, fn, precision, recall, and a list of bools
        indicating which GT boxes were detected.
    """
    gt_boxes = [yolo_to_xyxy(cx, cy, w, h, img_size)
                for _, cx, cy, w, h in gt_labels]

    n_gt = len(gt_boxes)
    n_pred = len(pred_boxes)

    # Edge cases
    if n_gt == 0 and n_pred == 0:
        return {"tp": 0, "fp": 0, "fn": 0,
                "precision": 1.0, "recall": 1.0, "gt_matched": []}
    if n_gt == 0:
        return {"tp": 0, "fp": n_pred, "fn": 0,
                "precision": 0.0, "recall": 1.0, "gt_matched": []}
    if n_pred == 0:
        return {"tp": 0, "fp": 0, "fn": n_gt,
                "precision": 1.0, "recall": 0.0,
                "gt_matched": [False] * n_gt}

    # Sort predictions by confidence (highest first)
    order = np.argsort(-pred_confs)
    pred_boxes_sorted = pred_boxes[order]

    gt_matched = [False] * n_gt
    tp = 0
    fp = 0

    for pred_box in pred_boxes_sorted:
        best_iou = 0.0
        best_idx = -1

        for gi, gt_box in enumerate(gt_boxes):
            if gt_matched[gi]:
                continue
            iou = compute_iou_xyxy(pred_box, gt_box)
            if iou > best_iou:
                best_iou = iou
                best_idx = gi

        if best_iou >= IOU_THRESHOLD and best_idx >= 0:
            tp += 1
            gt_matched[best_idx] = True
        else:
            fp += 1

    fn = sum(1 for m in gt_matched if not m)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 1.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 1.0

    return {
        "tp": tp, "fp": fp, "fn": fn,
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "gt_matched": gt_matched,
    }


# =============================================================================
# MATCH OBJECTS BETWEEN LABEL FILE AND METADATA CSV
#   The preprocessing pipeline writes YOLO labels and object_metadata.csv
#   in the same order.  As a safety measure we match by approximate centre
#   coordinates rather than relying on index alone.
# =============================================================================

def match_gt_to_metadata(
    gt_labels: List[Tuple[int, float, float, float, float]],
    meta_objects: List[Dict],
    img_size: int = 512,
    tol: float = 5.0,
) -> List[Optional[Dict]]:
    """
    For each GT label, find the best-matching metadata object by centre
    distance.  Returns a list parallel to gt_labels.
    """
    if not meta_objects:
        return [None] * len(gt_labels)

    matched: List[Optional[Dict]] = []
    used = set()

    for _, cx, cy, w, h in gt_labels:
        gt_cx_px = cx * img_size
        gt_cy_px = cy * img_size
        best_dist = float("inf")
        best_idx = None

        for mi, mo in enumerate(meta_objects):
            if mi in used:
                continue
            # object_metadata has centre coords already normalised
            mo_cx = float(mo.get("center_x_norm", 0)) * img_size
            mo_cy = float(mo.get("center_y_norm", 0)) * img_size
            dist = ((gt_cx_px - mo_cx) ** 2 + (gt_cy_px - mo_cy) ** 2) ** 0.5
            if dist < best_dist:
                best_dist = dist
                best_idx = mi

        if best_idx is not None and best_dist < tol:
            matched.append(meta_objects[best_idx])
            used.add(best_idx)
        else:
            matched.append(None)

    return matched


# =============================================================================
# FULL EVALUATION PIPELINE
# =============================================================================

def run_evaluation(
    weights_path: str,
    modality: str = "visible",
    conf: float = DEFAULT_CONF,
):
    """
    1. Load model and predict on validation images
    2. Match predictions to ground truth
    3. Merge with preprocessing metadata
    4. Compute subgroup metrics
    5. Export to CSVs
    """
    print("=" * 70)
    print(f"EVALUATION: Subgroup Analysis -- {modality.upper()}")
    print("=" * 70)

    os.makedirs(EVAL_OUTPUT_DIR, exist_ok=True)

    # --- Load model ---
    model = YOLO(weights_path)
    print(f"Loaded model: {weights_path}")

    # --- Locate validation images ---
    val_img_dir = os.path.join(
        DATASET_ROOT, "images", modality, "val"
    )
    labels_dir = os.path.join(
        DATASET_ROOT, "labels", modality, "val"
    )
    if not os.path.exists(val_img_dir):
        print(f"ERROR: Validation directory not found: {val_img_dir}")
        return

    img_files = sorted([
        f for f in os.listdir(val_img_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ])
    print(f"Found {len(img_files)} validation images in {val_img_dir}")

    # --- Load preprocessing metadata ---
    # Try to use the exact modality.  If no rows exist in the CSVs for that
    # modality (e.g. greyscale_inversion was never processed by the pipeline),
    # fall back to 'visible', whose set IDs and annotation labels are identical.
    def _pick_meta_modality(df: pd.DataFrame, target: str) -> str:
        if target in df["modality"].values:
            return target
        fallback = "visible"
        print(f"  NOTE: no metadata rows for '{target}'; "
              f"falling back to '{fallback}' (same KAIST set IDs / labels).")
        return fallback

    frame_meta: Dict[str, Dict] = {}
    if os.path.exists(FRAME_METADATA_CSV):
        df_fm = pd.read_csv(FRAME_METADATA_CSV)
        meta_modality = _pick_meta_modality(df_fm, modality)
        df_fm = df_fm[
            (df_fm["modality"] == meta_modality) & (df_fm["split"] == "val")
        ]
        frame_meta = {
            row["flat_name"]: row.to_dict() for _, row in df_fm.iterrows()
        }
        print(f"Loaded frame metadata: {len(frame_meta)} entries "
              f"(modality='{meta_modality}')")

    object_meta: Dict[str, List[Dict]] = {}
    if os.path.exists(OBJECT_METADATA_CSV):
        df_om = pd.read_csv(OBJECT_METADATA_CSV)
        meta_modality_obj = _pick_meta_modality(df_om, modality)
        df_om = df_om[
            (df_om["modality"] == meta_modality_obj) & (df_om["split"] == "val")
        ]
        for flat_name, group in df_om.groupby("flat_name"):
            object_meta[flat_name] = group.to_dict("records")
        print(f"Loaded object metadata: {len(df_om)} objects across "
              f"{len(object_meta)} frames (modality='{meta_modality_obj}')")

    # --- Run predictions & evaluate ---
    print(f"\nRunning predictions (conf={conf}, iou_thresh={IOU_THRESHOLD})...")

    per_image_rows = []
    per_object_rows = []

    for img_file in img_files:
        flat_name = os.path.splitext(img_file)[0]
        img_path = os.path.join(val_img_dir, img_file)

        # Predict
        results = model.predict(
            img_path, conf=conf, iou=0.45, imgsz=512, verbose=False,
        )
        result = results[0]

        pred_boxes = (result.boxes.xyxy.cpu().numpy()
                      if len(result.boxes) > 0 else np.empty((0, 4)))
        pred_confs = (result.boxes.conf.cpu().numpy()
                      if len(result.boxes) > 0 else np.empty(0))

        # Ground truth
        label_path = os.path.join(labels_dir, f"{flat_name}.txt")
        gt_labels = load_yolo_labels(label_path)

        # Per-image evaluation
        ev = evaluate_image(pred_boxes, pred_confs, gt_labels)

        # Load image for per-object quality features
        img_gray = load_image_grayscale(img_path)
        img_h, img_w = (img_gray.shape[:2]
                        if img_gray is not None else (512, 512))

        img_row = {
            "flat_name": flat_name,
            "modality": modality,
            "num_gt": len(gt_labels),
            "num_pred": len(pred_boxes),
            "tp": ev["tp"],
            "fp": ev["fp"],
            "fn": ev["fn"],
            "precision": ev["precision"],
            "recall": ev["recall"],
        }

        # Merge frame-level metadata
        if flat_name in frame_meta:
            fm = frame_meta[flat_name]
            img_row["day_night"] = fm.get("day_night", "unknown")
            img_row["brightness"] = fm.get("brightness", 0)
            img_row["contrast"] = fm.get("contrast", 0)
            img_row["edge_density"] = fm.get("edge_density", 0)
            img_row["num_people"] = fm.get("num_people", 0)
            img_row["num_overlapping_pairs"] = fm.get(
                "num_overlapping_pairs", 0)

        per_image_rows.append(img_row)

        # --- Per-object evaluation ---
        meta_objs = object_meta.get(flat_name, [])
        matched_meta = match_gt_to_metadata(gt_labels, meta_objs)

        for gi, (cls, cx, cy, w, h) in enumerate(gt_labels):
            detected = (ev["gt_matched"][gi]
                        if gi < len(ev["gt_matched"]) else False)

            obj_row = {
                "flat_name": flat_name,
                "modality": modality,
                "gt_idx": gi,
                "detected": detected,
                "gt_cx": round(cx, 4),
                "gt_cy": round(cy, 4),
                "gt_w": round(w, 4),
                "gt_h": round(h, 4),
            }

            mo = matched_meta[gi]
            if mo is not None:
                obj_row["size_category"] = mo.get("size_category", "unknown")
                obj_row["bbox_height_px"] = mo.get("bbox_height_px", 0)
                obj_row["bbox_width_px"] = mo.get("bbox_width_px", 0)
                obj_row["bbox_area_px"] = mo.get("bbox_area_px", 0)
                obj_row["occlusion"] = mo.get("occlusion", 0)
                obj_row["truncated"] = mo.get("truncated", 0)
                obj_row["has_overlap"] = mo.get("has_overlap", False)
                obj_row["dist_from_center"] = mo.get("dist_from_center", 0)
                obj_row["day_night"] = mo.get("day_night", "unknown")
                obj_row["aspect_ratio"] = mo.get("aspect_ratio", 0)
            else:
                # Fallback: use frame-level day_night if available
                obj_row["day_night"] = img_row.get("day_night", "unknown")

            # Per-object image quality features
            if img_gray is not None:
                px1, py1, px2, py2 = yolo_to_xyxy(cx, cy, w, h, img_w)
                px1 = max(0, int(round(px1)))
                py1 = max(0, int(round(py1)))
                px2 = min(img_w, int(round(px2)))
                py2 = min(img_h, int(round(py2)))
                qf = compute_object_quality_features(
                    img_gray, px1, py1, px2, py2, img_h, img_w)
                obj_row.update(qf)
            else:
                for key in ("object_brightness", "object_contrast",
                            "bg_brightness", "bg_contrast", "fg_bg_diff",
                            "object_edge_strength", "object_blur"):
                    obj_row[key] = float("nan")

            per_object_rows.append(obj_row)

    # --- Export per-image results ---
    img_csv = os.path.join(
        EVAL_OUTPUT_DIR, f"per_image_results_{modality}.csv")
    df_img = pd.DataFrame(per_image_rows)
    df_img.to_csv(img_csv, index=False)
    print(f"\nSaved per-image results: {img_csv} ({len(df_img)} rows)")

    # --- Export per-object results ---
    obj_csv = os.path.join(
        EVAL_OUTPUT_DIR, f"per_object_results_{modality}.csv")
    df_obj = pd.DataFrame(per_object_rows)
    df_obj.to_csv(obj_csv, index=False)
    print(f"Saved per-object results: {obj_csv} ({len(df_obj)} rows)")

    # --- Compute subgroup summary ---
    summary_csv = compute_subgroup_summary(df_img, df_obj, modality)
    print(f"Saved subgroup summary: {summary_csv}")

    # --- Print overview ---
    print_summary(df_img, df_obj)

    print(f"\nAll evaluation results saved to: {EVAL_OUTPUT_DIR}")


# =============================================================================
# SUBGROUP SUMMARY
#   Aggregate detection metrics across multiple grouping dimensions so the
#   thesis analysis can compare performance across subgroups.
# =============================================================================

def compute_subgroup_summary(
    df_img: pd.DataFrame,
    df_obj: pd.DataFrame,
    modality: str,
) -> str:
    """
    Compute and export detection metrics broken down by subgroup.

    Subgroups:
        - day_night (day / night)
        - size_category (small / medium / large)
        - occlusion (0 / 1 / 2)
        - truncated (0 / 1)
        - has_overlap (True / False)
        - crowd_bin (0 / 1 / 2 / 3 / 4 / 5+)

    For each subgroup, compute:
        - count       : number of GT objects in this group
        - detected    : number of detected GT objects
        - missed      : number of missed GT objects
        - recall      : detected / count
    """
    rows = []

    # Helper: compute recall for a filtered slice of per-object df
    def add_group(group_name, col, df):
        if col not in df.columns:
            return
        for val, sub in df.groupby(col):
            n = len(sub)
            det = int(sub["detected"].sum())
            rows.append({
                "subgroup_type": group_name,
                "subgroup_value": str(val),
                "count": n,
                "detected": det,
                "missed": n - det,
                "recall": round(det / n, 4) if n > 0 else 0.0,
            })

    add_group("day_night", "day_night", df_obj)
    add_group("size_category", "size_category", df_obj)
    add_group("occlusion", "occlusion", df_obj)
    add_group("truncated", "truncated", df_obj)
    add_group("has_overlap", "has_overlap", df_obj)

    # Crowd density bins from per-image data
    if "num_people" in df_img.columns:
        df_img_copy = df_img.copy()
        df_img_copy["crowd_bin"] = df_img_copy["num_people"].apply(
            lambda x: str(int(x)) if x <= 4 else "5+"
        )
        for val, sub in df_img_copy.groupby("crowd_bin"):
            tp_sum = int(sub["tp"].sum())
            fn_sum = int(sub["fn"].sum())
            fp_sum = int(sub["fp"].sum())
            total_gt = tp_sum + fn_sum
            prec = tp_sum / (tp_sum + fp_sum) if (tp_sum + fp_sum) > 0 else 0
            rec = tp_sum / total_gt if total_gt > 0 else 0
            rows.append({
                "subgroup_type": "crowd_density",
                "subgroup_value": val,
                "count": total_gt,
                "detected": tp_sum,
                "missed": fn_sum,
                "recall": round(rec, 4),
            })

    path = os.path.join(
        EVAL_OUTPUT_DIR, f"subgroup_summary_{modality}.csv")
    df_summary = pd.DataFrame(rows)
    df_summary.to_csv(path, index=False)
    return path


# =============================================================================
# SUMMARY PRINTOUT
# =============================================================================

def print_summary(df_img: pd.DataFrame, df_obj: pd.DataFrame):
    """Print a concise evaluation summary to the console."""
    total_tp = int(df_img["tp"].sum())
    total_fp = int(df_img["fp"].sum())
    total_fn = int(df_img["fn"].sum())
    total_gt = total_tp + total_fn

    overall_prec = total_tp / (total_tp + total_fp) if (total_tp + total_fp) > 0 else 0
    overall_rec = total_tp / total_gt if total_gt > 0 else 0
    f1 = (2 * overall_prec * overall_rec / (overall_prec + overall_rec)
          if (overall_prec + overall_rec) > 0 else 0)

    print(f"\n{'='*50}")
    print(f"OVERALL RESULTS")
    print(f"{'='*50}")
    print(f"  Total GT objects : {total_gt}")
    print(f"  True Positives   : {total_tp}")
    print(f"  False Positives  : {total_fp}")
    print(f"  False Negatives  : {total_fn}")
    print(f"  Precision        : {overall_prec:.4f}")
    print(f"  Recall           : {overall_rec:.4f}")
    print(f"  F1 Score         : {f1:.4f}")

    # Per-subgroup recall highlights
    if "day_night" in df_obj.columns:
        print(f"\n  Recall by Day/Night:")
        for dn, sub in df_obj.groupby("day_night"):
            n = len(sub)
            det = int(sub["detected"].sum())
            print(f"    {dn:>8s}: {det}/{n} = {det/n:.4f}" if n > 0 else f"    {dn}: n/a")

    if "size_category" in df_obj.columns:
        print(f"\n  Recall by Size:")
        for cat in ["small", "medium", "large"]:
            sub = df_obj[df_obj["size_category"] == cat]
            n = len(sub)
            det = int(sub["detected"].sum())
            if n > 0:
                print(f"    {cat:>8s}: {det}/{n} = {det/n:.4f}")


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Evaluate YOLOv8 with subgroup analysis"
    )
    parser.add_argument(
        "--modality", type=str, default="visible",
        choices=["visible", "thermal", "greyscale_inversion"],
    )
    parser.add_argument(
        "--weights", type=str, default=None,
        help="Path to model weights. Default: runs/kaist_{modality}/weights/best.pt"
    )
    parser.add_argument(
        "--conf", type=float, default=DEFAULT_CONF,
        help=f"Confidence threshold (default: {DEFAULT_CONF})"
    )
    args = parser.parse_args()

    if args.weights is None:
        args.weights = os.path.join(
            RUNS_DIR, f"kaist_{args.modality}", "weights", "best.pt"
        )

    if not os.path.exists(args.weights):
        print(f"ERROR: Weights not found: {args.weights}")
        print("Train the model first with train.py")
    else:
        run_evaluation(args.weights, args.modality, args.conf)
