"""
=============================================================================
YOLOv8 Training Script for KAIST Pedestrian Detection
=============================================================================

Trains a YOLOv8n model on the preprocessed KAIST visible-light (or thermal)
images. Hyperparameters were optimized with Optuna. Early stopping is enabled
with patience=15.

After training completes, weights are copied with epoch numbers:
    best_{epoch}.pt  -- weights from the best-performing epoch (by mAP50)
    last_{epoch}.pt  -- weights from the final training epoch

Usage:
    python train.py                         # Train on visible images
    python train.py --modality thermal      # Train on thermal images
    python train.py --resume                # Resume interrupted training

Output:
    OD/runs/kaist_{modality}/
    +-- weights/
    |   +-- best.pt  +  best_{epoch}.pt
    |   +-- last.pt  +  last_{epoch}.pt
    +-- results.csv          (per-epoch loss & metric values)
    +-- confusion_matrix.png (auto-generated by ultralytics)
    +-- ...
=============================================================================
"""

import argparse
import os
import shutil

import pandas as pd
from ultralytics import YOLO
from ultralytics.utils.callbacks import Callbacks


# =============================================================================
# PATHS
# =============================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

# Pretrained weights
WEIGHTS_PATH = os.path.join(SCRIPT_DIR, "yolov8n.pt")

# Dataset configs generated by the preprocessing pipeline
DATASET_ROOT = os.path.join(PROJECT_ROOT, "datasets", "kaist_processed")
DATASET_YAML = {
    "visible": os.path.join(DATASET_ROOT, "kaist_visible.yaml"),
    "thermal": os.path.join(DATASET_ROOT, "kaist_thermal.yaml"),
    "greyscale_inversion": os.path.join(DATASET_ROOT, "kaist_greyscale_inversion.yaml"),
}

# Training output directory
RUNS_DIR = os.path.join(SCRIPT_DIR, "runs")


# =============================================================================
# OPTUNA-OPTIMIZED HYPERPARAMETERS
# =============================================================================

HYPERPARAMS = {
    "epochs": 15,
    "patience": 15,
    "imgsz": 512,
    "batch": 64,
    "lr0": 0.003175673197442611,
    "weight_decay": 0.00010299214204601986,
    "momentum": 0.9085426764391346,
    "optimizer": "SGD",
    "seed": 42,
    "rect": True,
}


# =============================================================================
# EPOCH TRACKING CALLBACK
# =============================================================================

class BestEpochCallback(Callbacks):
    """Print the current best epoch after each training epoch."""

    def __init__(self, run_dir: str):
        super().__init__()
        self.run_dir = run_dir
        self.results_csv = os.path.join(run_dir, "results.csv")
        self.last_best_epoch = None

    def on_train_epoch_end(self, trainer):
        """Called at the end of each training epoch."""
        if not os.path.exists(self.results_csv):
            return

        try:
            df = pd.read_csv(self.results_csv)
            df.columns = [c.strip() for c in df.columns]

            if "metrics/mAP50(B)" not in df.columns:
                return

            best_idx = df["metrics/mAP50(B)"].idxmax()
            best_epoch = best_idx + 1
            best_map50 = df["metrics/mAP50(B)"].iloc[best_idx]
            current_epoch = len(df)

            if best_epoch != self.last_best_epoch:
                print(
                    f"\n>>> Epoch {current_epoch}/{trainer.epochs} — "
                    f"NEW BEST: Epoch {best_epoch} (mAP50: {best_map50:.4f})\n"
                )
                self.last_best_epoch = best_epoch
            # else: silently continue if best hasn't changed

        except Exception as e:
            # Silently skip if CSV is corrupted or incomplete
            pass


def train(modality: str = "visible", resume: bool = False,
          data_yaml: str = None):
    """
    Train YOLOv8n on the KAIST dataset.

    Args:
        modality: "visible" or "thermal"
        resume: If True, resume from the last checkpoint.
        data_yaml: Optional override for the dataset YAML path.
                   Useful when running inside Docker where paths differ.

    Returns:
        ultralytics Results object, or None on error.
    """
    print("=" * 70)
    print(f"TRAINING YOLOv8n -- {modality.upper()} modality")
    print("=" * 70)

    # Verify dataset config exists
    yaml_path = data_yaml if data_yaml else DATASET_YAML[modality]
    if not os.path.exists(yaml_path):
        print(f"ERROR: Dataset config not found: {yaml_path}")
        print("Run the preprocessing pipeline first (preprocessing/main.py)")
        return None

    run_name = f"kaist_{modality}"

    # Load model (resume from checkpoint or start fresh)
    if resume:
        last_pt = os.path.join(RUNS_DIR, run_name, "weights", "last.pt")
        if not os.path.exists(last_pt):
            print(f"ERROR: No checkpoint to resume from: {last_pt}")
            return None
        model = YOLO(last_pt)
        print(f"Resuming from: {last_pt}")
    else:
        model = YOLO(WEIGHTS_PATH)
        print(f"Starting from pretrained: {WEIGHTS_PATH}")

    print(f"Dataset config: {yaml_path}")
    print(f"Output directory: {os.path.join(RUNS_DIR, run_name)}")
    print(f"\nHyperparameters:")
    for k, v in HYPERPARAMS.items():
        print(f"  {k}: {v}")

    # Create callback to track best epoch
    run_dir = os.path.join(RUNS_DIR, run_name)
    callback = BestEpochCallback(run_dir)

    # Train
    results = model.train(
        data=yaml_path,
        project=RUNS_DIR,
        name=run_name,
        exist_ok=True,
        save=True,
        plots=True,
        callbacks=[callback],
        **HYPERPARAMS,
    )

    # Rename weights with epoch numbers
    rename_weights(run_name)

    print("\nTraining complete.")
    return results


# =============================================================================
# WEIGHT RENAMING
#   After training, copy best.pt and last.pt with the epoch number in the
#   filename so it is easy to identify which epoch the weights belong to.
# =============================================================================

def rename_weights(run_name: str):
    """
    Copy best.pt -> best_{epoch}.pt and last.pt -> last_{epoch}.pt
    based on the results.csv written by ultralytics.
    """
    run_dir = os.path.join(RUNS_DIR, run_name)
    weights_dir = os.path.join(run_dir, "weights")
    results_csv = os.path.join(run_dir, "results.csv")

    if not os.path.exists(results_csv):
        print("WARNING: results.csv not found, cannot rename weights.")
        return

    df = pd.read_csv(results_csv)
    df.columns = [c.strip() for c in df.columns]

    last_epoch = len(df)

    # Best epoch = row with highest mAP50
    if "metrics/mAP50(B)" in df.columns:
        best_epoch = int(df["metrics/mAP50(B)"].idxmax()) + 1
    else:
        print("WARNING: mAP50 column not found in results.csv")
        best_epoch = last_epoch

    print(f"\nBest epoch: {best_epoch} (by mAP50)")
    print(f"Last epoch: {last_epoch}")

    best_src = os.path.join(weights_dir, "best.pt")
    last_src = os.path.join(weights_dir, "last.pt")

    if os.path.exists(best_src):
        best_dst = os.path.join(weights_dir, f"best_{best_epoch}.pt")
        shutil.copy2(best_src, best_dst)
        print(f"Saved: {best_dst}")

    if os.path.exists(last_src):
        last_dst = os.path.join(weights_dir, f"last_{last_epoch}.pt")
        shutil.copy2(last_src, last_dst)
        print(f"Saved: {last_dst}")


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train YOLOv8 on KAIST pedestrian dataset"
    )
    parser.add_argument(
        "--modality", type=str, default="visible",
        choices=["visible", "thermal", "greyscale_inversion"],
    )
    parser.add_argument(
        "--resume", action="store_true",
        help="Resume training from last checkpoint"
    )
    parser.add_argument(
        "--data", type=str, default=None,
        help="Override path to dataset YAML (for Docker or custom setups)"
    )
    args = parser.parse_args()

    train(args.modality, args.resume, args.data)
