"""
=============================================================================
YOLOv8 Training Script for KAIST Pedestrian Detection & PID Dataset
=============================================================================

Trains a YOLOv8n model on the preprocessed KAIST visible-light (or thermal)
images, or on the PID dataset. Hyperparameters can be optimised with the
built-in Optuna search (--tune), then used directly for a full 800-epoch run.

After training completes, weights are copied with epoch numbers:
    best_{epoch}.pt  -- weights from the best-performing epoch (by mAP50)
    last_{epoch}.pt  -- weights from the final training epoch

Usage:
    python train.py                                   # Train on visible
    python train.py --modality greyscale_inversion    # Train on greyscale
    python train.py --modality pid                    # Train on PID dataset
    python train.py --resume                          # Resume training
    python train.py --tune                            # Optuna search (50 trials)
    python train.py --tune --trials 100 --tune-epochs 20  # Custom search

Output:
    OD/runs/kaist_{modality}/ or OD/runs/pid/
    +-- weights/
    |   +-- best.pt  +  best_{epoch}.pt
    |   +-- last.pt  +  last_{epoch}.pt
    +-- results.csv          (per-epoch loss & metric values)
    +-- confusion_matrix.png (auto-generated by ultralytics)
    +-- ...
=============================================================================
"""

import argparse
import json
import os
import shutil
import tempfile

import pandas as pd
import yaml
from ultralytics import YOLO


# =============================================================================
# PATHS
# =============================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

# Pretrained weights
WEIGHTS_PATH = os.path.join(SCRIPT_DIR, "yolov8n.pt")

# Dataset configs generated by the preprocessing pipeline
DATASET_ROOT = os.path.join(PROJECT_ROOT, "datasets", "kaist_processed")
PID_DATASET = os.path.join(PROJECT_ROOT, "datasets", "PID", "pid.yaml")
PI_GAN_DATASET = os.path.join(PROJECT_ROOT, "datasets", "PI-GAN", "pi_gan.yaml")
DATASET_YAML = {
    "visible": os.path.join(DATASET_ROOT, "kaist_visible.yaml"),
    "thermal": os.path.join(DATASET_ROOT, "kaist_thermal.yaml"),
    "greyscale_inversion": os.path.join(DATASET_ROOT, "kaist_greyscale_inversion.yaml"),
    "PI-GAN_gen": os.path.join(DATASET_ROOT, "kaist_pigan.yaml"),
    "pid": PID_DATASET,
    "pi-gan": PI_GAN_DATASET,
}

# Training output directory
RUNS_DIR = os.path.join(SCRIPT_DIR, "runs")


# =============================================================================
# OPTUNA-OPTIMIZED HYPERPARAMETERS
# =============================================================================

HYPERPARAMS = {
    "epochs": 800,
    "patience": 8,
    "imgsz": 512,
    "batch": 64,
    "lr0": 0.008691379140720273,
    "weight_decay": 0.00020821934265337954,
    "momentum": 0.8512264928571917,
    "optimizer": "SGD",
    "seed": 42,
}

# PI-GAN specific hyperparameters from Optuna (trial #14, mAP50=0.8353)
PI_GAN_HYPERPARAMS = {
    "epochs": 800,
    "patience": 10,
    "imgsz": 512,
    "seed": 42,
    "batch": 64,
    "optimizer": "AdamW",
    "lr0": 0.002863527111494497,
    "weight_decay": 2.9653955672573863e-06,
    "momentum": 0.7001237139162004,
    "warmup_epochs": 4,
    "box": 5.30859869833292,
    "cls": 0.9864929265634742,
    "hsv_h": 0.03897767816292479,
    "hsv_s": 0.10550162188408234,
    "hsv_v": 0.7311958141614289,
    "fliplr": 0.004510238535283168,
    "mosaic": 0.6471358807190548,
}


# =============================================================================
# EPOCH TRACKING CALLBACK
# =============================================================================

# =============================================================================
# DATASET YAML HELPER
# =============================================================================

def _make_dataset_yaml(modality: str, data_yaml: str = None) -> str:
    """
    Return a path to a temp YAML whose 'path' field is set to the absolute
    directory of the source YAML file, so Ultralytics resolves train/val
    correctly regardless of the current working directory.
    """
    src = data_yaml if data_yaml else DATASET_YAML[modality]
    with open(src, "r") as f:
        cfg = yaml.safe_load(f)
    cfg["path"] = str(os.path.dirname(os.path.abspath(src)))
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False)
    yaml.dump(cfg, tmp)
    tmp.close()
    return tmp.name


class BestEpochCallback:
    """Print current and best epoch info and write training_log.csv after every epoch."""

    def __init__(self, run_dir: str):
        self.run_dir = run_dir
        self.results_csv = os.path.join(run_dir, "results.csv")
        self.log_csv = os.path.join(run_dir, "training_log.csv")
        self.last_best_epoch = None
        self.log_rows = []

    def on_train_epoch_end(self, trainer):
        """Called at the end of each training epoch."""
        epoch = trainer.epoch + 1  # trainer.epoch is 0-indexed

        # --- Write our own incremental CSV from trainer state ---
        try:
            row = {"epoch": epoch}
            # Loss values
            if hasattr(trainer, "loss_items") and trainer.loss_items is not None:
                loss_names = getattr(trainer, "loss_names",
                                     ["box_loss", "cls_loss", "dfl_loss"])
                for name, val in zip(loss_names, trainer.loss_items):
                    row[f"train/{name}"] = float(val)
            # Val metrics (available one epoch behind on first call, but
            # trainer.metrics is populated by on_val_end which fires before this)
            if hasattr(trainer, "metrics") and trainer.metrics:
                for k, v in trainer.metrics.items():
                    row[k] = float(v) if v is not None else None
            self.log_rows.append(row)
            log_df = pd.DataFrame(self.log_rows)
            log_df.to_csv(self.log_csv, index=False)
        except Exception:
            pass

        # --- Print best-epoch summary (reads Ultralytics results.csv if present) ---
        try:
            src = self.results_csv if os.path.exists(self.results_csv) else self.log_csv
            df = pd.read_csv(src)
            df.columns = [c.strip() for c in df.columns]

            map_col = next((c for c in df.columns if "mAP50" in c and "95" not in c), None)
            if map_col is None:
                return

            current_map50 = df[map_col].iloc[-1]
            best_idx = df[map_col].idxmax()
            best_epoch = best_idx + 1
            best_map50 = df[map_col].iloc[best_idx]

            is_new_best = best_epoch != self.last_best_epoch
            self.last_best_epoch = best_epoch

            marker = " << NEW BEST" if is_new_best else ""
            print(
                f"\n>>> Epoch {epoch}/{trainer.epochs} — "
                f"mAP50: {current_map50:.4f} | "
                f"Best: Epoch {best_epoch} (mAP50: {best_map50:.4f}){marker}\n"
            )
        except Exception:
            pass


def train(modality: str = "visible", resume: bool = False,
          data_yaml: str = None):
    """
    Train YOLOv8n on the KAIST dataset or PID dataset.

    Args:
        modality: "visible", "thermal", "pid", or other variants
        resume: If True, resume from the last checkpoint.
        data_yaml: Optional override for the dataset YAML path.
                   Useful when running inside Docker where paths differ.

    Returns:
        ultralytics Results object, or None on error.
    """
    print("=" * 70)
    print(f"TRAINING YOLOv8n -- {modality.upper()} modality")
    print("=" * 70)

    # Verify dataset config exists
    src_yaml = data_yaml if data_yaml else DATASET_YAML.get(modality)
    if src_yaml is None:
        print(f"ERROR: Unknown modality: {modality}")
        return None
    if not os.path.exists(src_yaml):
        print(f"ERROR: Dataset config not found: {src_yaml}")
        if modality != "pid":
            print("Run the preprocessing pipeline first (preprocessing/main.py)")
        return None

    yaml_path = _make_dataset_yaml(modality, data_yaml)
    run_name = f"pid" if modality == "pid" else f"kaist_{modality}"

    # Select hyperparameters based on modality
    hparams = PI_GAN_HYPERPARAMS if modality == "pi-gan" else HYPERPARAMS

    # Load model (resume from checkpoint or start fresh)
    if resume:
        last_pt = os.path.join(RUNS_DIR, run_name, "weights", "last.pt")
        if not os.path.exists(last_pt):
            print(f"ERROR: No checkpoint to resume from: {last_pt}")
            return None
        model = YOLO(last_pt)
        print(f"Resuming from: {last_pt}")
    else:
        model = YOLO(WEIGHTS_PATH)
        print(f"Starting from pretrained: {WEIGHTS_PATH}")

    print(f"Dataset config: {yaml_path}")
    print(f"Output directory: {os.path.join(RUNS_DIR, run_name)}")
    print(f"\nHyperparameters:")
    for k, v in hparams.items():
        print(f"  {k}: {v}")

    # Create callbacks
    run_dir = os.path.join(RUNS_DIR, run_name)
    callback = BestEpochCallback(run_dir)
    model.add_callback("on_train_epoch_end", callback.on_train_epoch_end)
    # Train
    results = model.train(
        data=yaml_path,
        project=RUNS_DIR,
        name=run_name,
        exist_ok=True,
        save=True,
        plots=True,
        resume=resume,
        **hparams,
    )

    # Rename weights with epoch numbers
    rename_weights(run_name)

    print("\nTraining complete.")
    return results


# =============================================================================
# OPTUNA HYPERPARAMETER SEARCH
# =============================================================================

def optimize(modality: str = "visible", n_trials: int = 50,
             tune_epochs: int = 30, data_yaml: str = None,
             timeout_seconds: int = None):
    """
    Run an Optuna study to find the best hyperparameters for the given modality.

    Each trial trains for `tune_epochs` epochs and reports the best mAP50.
    Results are saved to OD/runs/optuna_{modality}/.

    Args:
        modality:    Dataset modality (visible / thermal / greyscale_inversion)
        n_trials:    Number of Optuna trials to run
        tune_epochs: Epochs per trial (short runs, e.g. 20-50)
        data_yaml:   Optional dataset YAML override
    """
    try:
        import optuna
        optuna.logging.set_verbosity(optuna.logging.WARNING)
    except ImportError:
        print("ERROR: optuna is not installed. Run: pip install optuna")
        return None

    src_yaml = data_yaml if data_yaml else DATASET_YAML[modality]
    if not os.path.exists(src_yaml):
        print(f"ERROR: Dataset config not found: {src_yaml}")
        return None

    yaml_path = _make_dataset_yaml(modality, data_yaml)
    study_dir = os.path.join(RUNS_DIR, f"optuna_{modality}")
    os.makedirs(study_dir, exist_ok=True)

    print("=" * 70)
    print(f"OPTUNA SEARCH -- {modality.upper()} -- {n_trials} trials x {tune_epochs} epochs")
    print("=" * 70)

    def objective(trial):
        params = {
            "epochs":        tune_epochs,
            "patience":      tune_epochs,
            "imgsz":         512,
            "seed":          42,
            "rect":          True,
            "batch":         trial.suggest_categorical("batch", [32, 64]),
            "optimizer":     trial.suggest_categorical("optimizer", ["SGD", "Adam", "AdamW"]),
            "lr0":           trial.suggest_float("lr0", 1e-4, 1e-1, log=True),
            "weight_decay":  trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "momentum":      trial.suggest_float("momentum", 0.7, 0.99),
            "warmup_epochs": trial.suggest_int("warmup_epochs", 1, 5),
            "box":           trial.suggest_float("box", 4.0, 10.0),
            "cls":           trial.suggest_float("cls", 0.3, 1.5),
            "hsv_h":         trial.suggest_float("hsv_h", 0.0, 0.1),
            "hsv_s":         trial.suggest_float("hsv_s", 0.0, 0.9),
            "hsv_v":         trial.suggest_float("hsv_v", 0.0, 0.9),
            "fliplr":        trial.suggest_float("fliplr", 0.0, 0.5),
            "mosaic":        trial.suggest_float("mosaic", 0.5, 1.0),
        }

        trial_run = os.path.join(study_dir, f"trial_{trial.number}")
        model = YOLO(WEIGHTS_PATH)
        try:
            model.train(
                data=yaml_path,
                project=study_dir,
                name=f"trial_{trial.number}",
                exist_ok=True,
                save=False,
                plots=False,
                verbose=False,
                **params,
            )
            results_csv = os.path.join(trial_run, "results.csv")
            if os.path.exists(results_csv):
                df = pd.read_csv(results_csv)
                df.columns = [c.strip() for c in df.columns]
                if "metrics/mAP50(B)" in df.columns:
                    return float(df["metrics/mAP50(B)"].max())
        except Exception as e:
            print(f"  Trial {trial.number} failed: {e}")
        return 0.0

    study = optuna.create_study(
        direction="maximize",
        study_name=f"kaist_{modality}",
        sampler=optuna.samplers.TPESampler(seed=42),
    )
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    print("\n" + "=" * 70)
    print("OPTUNA SEARCH COMPLETE")
    print("=" * 70)
    print(f"Best trial : #{study.best_trial.number}")
    print(f"Best mAP50 : {study.best_value:.4f}")
    print("Best params:")
    for k, v in study.best_params.items():
        print(f"  {k}: {v}")

    # Persist results
    out = {"best_map50": study.best_value, "params": study.best_params}
    best_path = os.path.join(study_dir, "best_params.json")
    with open(best_path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nBest params saved to: {best_path}")

    try:
        study.trials_dataframe().to_csv(
            os.path.join(study_dir, "trials.csv"), index=False
        )
    except Exception:
        pass

    return study.best_params


# =============================================================================
# WEIGHT RENAMING
#   After training, copy best.pt and last.pt with the epoch number in the
#   filename so it is easy to identify which epoch the weights belong to.
# =============================================================================

def rename_weights(run_name: str):
    """
    Copy best.pt -> best_{epoch}.pt and last.pt -> last_{epoch}.pt
    based on the results.csv written by ultralytics.
    """
    run_dir = os.path.join(RUNS_DIR, run_name)
    weights_dir = os.path.join(run_dir, "weights")
    results_csv = os.path.join(run_dir, "results.csv")

    if not os.path.exists(results_csv):
        print("WARNING: results.csv not found, cannot rename weights.")
        return

    df = pd.read_csv(results_csv)
    df.columns = [c.strip() for c in df.columns]

    last_epoch = len(df)

    # Best epoch = row with highest mAP50
    if "metrics/mAP50(B)" in df.columns:
        best_epoch = int(df["metrics/mAP50(B)"].idxmax()) + 1
    else:
        print("WARNING: mAP50 column not found in results.csv")
        best_epoch = last_epoch

    print(f"\nBest epoch: {best_epoch} (by mAP50)")
    print(f"Last epoch: {last_epoch}")

    best_src = os.path.join(weights_dir, "best.pt")
    last_src = os.path.join(weights_dir, "last.pt")

    if os.path.exists(best_src):
        best_dst = os.path.join(weights_dir, f"best_{best_epoch}.pt")
        shutil.copy2(best_src, best_dst)
        print(f"Saved: {best_dst}")

    if os.path.exists(last_src):
        last_dst = os.path.join(weights_dir, f"last_{last_epoch}.pt")
        shutil.copy2(last_src, last_dst)
        print(f"Saved: {last_dst}")


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train YOLOv8 on KAIST pedestrian dataset"
    )
    parser.add_argument(
        "--modality", type=str, default="visible",
        choices=["visible", "thermal", "greyscale_inversion", "PI-GAN_gen", "pid", "pi-gan"],
    )
    parser.add_argument(
        "--resume", action="store_true",
        help="Resume training from last checkpoint"
    )
    parser.add_argument(
        "--data", type=str, default=None,
        help="Override path to dataset YAML (for Docker or custom setups)"
    )
    parser.add_argument(
        "--tune", action="store_true",
        help="Run Optuna hyperparameter search instead of training"
    )
    parser.add_argument(
        "--trials", type=int, default=50,
        help="Number of Optuna trials (default: 50)"
    )
    parser.add_argument(
        "--tune-epochs", type=int, default=30,
        help="Epochs per Optuna trial (default: 30)"
    )
    args = parser.parse_args()

    if args.tune:
        optimize(args.modality, args.trials, args.tune_epochs, args.data)
    else:
        train(args.modality, args.resume, args.data)
